version: '3.8'

services:
  csharp-learning-hub:
    build: .
    ports:
      - "9056:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: csharp-learning-hub
    networks:
      - app-network

networks:
  app-network:
    driver: bridge