version: '3.8'

services:
  learning-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner  # Build up to the final stage
    ports:
      - "9056:9056"
    container_name: learning-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  default:
    name: learning-network
