version: '3.8'

services:
  learning-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9056:9056"
    restart: unless-stopped
    container_name: learning-app
    environment:
      - NODE_ENV=production

networks:
  default:
    name: learning-network